src/LotteryService.FrontEnd/Controllers/DepartmentController.cs
using LotteryService.FrontEnd.Models.DTO;
using LotteryService.FrontEnd.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace LotteryService.FrontEnd.Controllers
{
    /// <summary>
    /// Управление подразделениями Общества.
    /// </summary>
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }
        
        public async Task<IActionResult> Index()
        {
            return View(await _departmentService.GetAllDepartments());
        }
        
        
        public async Task<IActionResult> Details(Guid id)
        {
            return View(await _departmentService.GetDepartmentById(id));
        }
        
        [HttpGet]
        public  IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Создать подразделение 
        /// </summary>
        /// <param name="department"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create(CreateOrUpdateDepartmentDto department)
        {
            await _departmentService.AddDepartmentAsync(department);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            return View(await _departmentService.GetDepartmentForUpdateById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, CreateOrUpdateDepartmentDto department)
        {
            await _departmentService.UpdateDepartmentAsync(id, department);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> DepartmentForDelete(Guid id)
        {
            return View(await _departmentService.GetDepartmentById(id));
        }

        
        public async Task<IActionResult> Delete(Guid id)
        {
            await _departmentService.RemoveDepartmentAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/LotteryService.FrontEnd/Controllers/EmployeeController.cs
using LotteryService.FrontEnd.Models.DTO;
using LotteryService.FrontEnd.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using AutoMapper;
using LotteryService.FrontEnd.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace LotteryService.FrontEnd.Controllers
{
    /// <summary>
    /// Управление сотрудниками Общества.
    /// </summary>
    
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IDepartmentService _departmentService;
        private readonly IWebHostEnvironment _env;

        public EmployeeController(IEmployeeService employeeService, IDepartmentService departmentService, IWebHostEnvironment env)
        {
            _employeeService = employeeService;
            _departmentService = departmentService;
            _env = env;
        }
        
        public async Task<IActionResult> Index()
        {
            var employees = await _employeeService.GetAllEmployeesWithDepartments();
            return View(employees);
        }
        
        [HttpGet]
        public  IActionResult Search()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Search(int number)
        {
            var emp = await _employeeService.GetEmployeeByPersonalNumber(number);
            return PartialView("_Search", emp);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            return View(await _employeeService.GetEmployeeWithDepartmentById(id));
        }
        
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var departments = await _departmentService.GetAllDepartments();
            var listDepartments = new List<SelectListItem>();

            foreach (DepartmentResponseDto dep in departments)
            {
                var item = new SelectListItem {Text = dep.Name, Value = dep.Id.ToString()};
                listDepartments.Add(item);
            }
            ViewBag.Departments = listDepartments;
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(CreateOrUpdateEmployeeDto employee)
        {
            await _employeeService.AddEmployeeAsync(await SavePhoto(employee));
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var departments = await _departmentService.GetAllDepartments();
            var listDepartments = new List<SelectListItem>();

            foreach (DepartmentResponseDto dep in departments)
            {
                var item = new SelectListItem {Text = dep.Name, Value = dep.Id.ToString()};
                listDepartments.Add(item);
            }

            ViewBag.Departments = listDepartments;
            return View(await _employeeService.GetEmployeeForUpdate(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, CreateOrUpdateEmployeeDto employee)
        {
            await _employeeService.UpdateEmployeeAsync(id, await SavePhoto(employee));
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> EmployeeForDelete(Guid id)
        {
            return View(await _employeeService.GetEmployeeById(id));
        }
        
       
        public async Task<IActionResult> Delete(Guid id)
        {
            await _employeeService.RemoveEmployeeAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<CreateOrUpdateEmployeeDto> SavePhoto(CreateOrUpdateEmployeeDto employee)
        {
            if (employee.Photo != null)
            {
                var extension = "." + employee.Photo.FileName.Split('.')[employee.Photo.FileName.Split('.').Length - 1];
                var filename = Guid.NewGuid().ToString() + '_' + employee.SecondName + '_' + employee.Name + '_' +
                               employee.ThirdName + extension;
                var directory = Path.Combine(_env.WebRootPath, "EmployeePhotos");
                if (!Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                var path = Path.Combine(_env.WebRootPath, "EmployeePhotos", filename);

                await using (var stream = new FileStream(path, FileMode.Create))
                {
                    await employee.Photo.CopyToAsync(stream);
                }
                employee.PhotoPath = filename;
            }
            else
            {
                employee.PhotoPath = "";
            }

            return employee;
        }
    }
}

src/LotteryService.FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - LotteryService.FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Газпром добыча Ямбург</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Search">Поиск</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Сотрудники</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Подразделения</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; Сервис для проведения лотерей среди работников Общества- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/LotteryService.FrontEnd/Views/Shared/person.cshtml
@using LotteryService.FrontEnd.Models.DTO
@model EmployeeResponseDto

<div>
    <h1>Сотрудник</h1>
    
    <hr/>
    <img src="~/EmployeePhotos/@Model.PhotoPath" class="rounded-circle" width="200" height="200" asp-append-version="true"/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SecondName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ThirdName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ThirdName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonalNumber)
        </dd>
    </dl>
</div>